name: release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    uses: compliance-framework/workflows/.github/workflows/release-policies.yml@899dbe5d7dac02de5fd60a92d764b189259e03dd # v1.5.0
    with:
      directory: policies
      opa-version: "1.14.1"
    permissions:
      contents: read
      packages: write
    secrets: inherit
