name: release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    uses: compliance-framework/workflows/.github/workflows/release-policies.yml@ec58cea2c02f12b5dad6b23a7bfdc84360f59f11 # v1.3.0
    with:
      directory: policies
      opa-version: "1.14.1"
    permissions:
      contents: read
      packages: write
    secrets: inherit
