name: release-please

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: release-please

jobs:
  release-please:
    uses: compliance-framework/workflows/.github/workflows/release-please.yml@ra/w1-s1-t05b-repo-settings-workflow
    permissions:
      contents: read
    secrets: inherit
