name: release-please

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: release-please

jobs:
  release-please:
    uses: compliance-framework/workflows/.github/workflows/release-please.yml@main
    permissions:
      contents: read
    secrets: inherit
